/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bubblegame;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author ScanNorOne
 */
public class MainForm extends javax.swing.JFrame {

    Logic logic;
    final int bubbleSize = 30;
    final Color backgrountColor = new Color(255, 255, 204);
    
    public MainForm() {
        initComponents();
        logic = Logic.getInstance();
        logic.initField();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        drawField();
    }
    
    public void drawField() {
        Graphics g = fieldPanel.getGraphics();
        for (int i = 0; i < logic.getCountRow(); i++)
            for (int j = 0; j < logic.getCountColumn(); j++) {
                if (logic.getFieldCell(i, j) != -1) {
                    g.setColor(getColor(logic.getFieldCell(i, j)));
                    g.fillOval(j * bubbleSize, i * bubbleSize, bubbleSize, bubbleSize);
                } else {
                    g.setColor(backgrountColor);
                    g.fillRect(j * bubbleSize, i * bubbleSize, bubbleSize, bubbleSize);
                }
            }
    }
    
    public Color getColor(int colorCode) {
        switch (colorCode) {
            case Logic.redBubble: return Color.RED;
            case Logic.greenBubble: return Color.GREEN;
            default: return Color.BLUE;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bubble Game");
        setResizable(false);

        fieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        fieldPanel.setPreferredSize(new java.awt.Dimension(300, 450));
        fieldPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fieldPanelLayout = new javax.swing.GroupLayout(fieldPanel);
        fieldPanel.setLayout(fieldPanelLayout);
        fieldPanelLayout.setHorizontalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        fieldPanelLayout.setVerticalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPanelMouseClicked
        Point point = fieldPanel.getMousePosition();
        logic.processing(point, bubbleSize);
        drawField();
    }//GEN-LAST:event_fieldPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fieldPanel;
    // End of variables declaration//GEN-END:variables
}
